# Generated by Django 5.1.2 on 2024-11-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfk_app', '0002_likemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='count',
        ),
        migrations.RemoveField(
            model_name='likemodel',
            name='user',
        ),
    ]
