# Generated by Django 5.1.2 on 2024-11-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfk_app', '0004_likemodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likemodel',
            old_name='user',
            new_name='users',
        ),
    ]
