# Generated by Django 5.1.2 on 2024-11-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfk_app', '0006_a_b_c'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
        migrations.DeleteModel(
            name='B',
        ),
        migrations.DeleteModel(
            name='C',
        ),
    ]
