# Generated by Django 5.1.2 on 2024-11-17 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookmodel',
            managers=[
            ],
        ),
    ]
